// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtONvghfazXAXaBPMAlUvWFbJmb_bgo3w',
    appId: '1:313647268069:web:9a1c522267cac45909540c',
    messagingSenderId: '313647268069',
    projectId: 'messaging-app-67bf2',
    authDomain: 'messaging-app-67bf2.firebaseapp.com',
    storageBucket: 'messaging-app-67bf2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzzjo7FffsNOAXwYkQXl1JnD-JzcI6zXI',
    appId: '1:313647268069:android:9efd92296138ecef09540c',
    messagingSenderId: '313647268069',
    projectId: 'messaging-app-67bf2',
    storageBucket: 'messaging-app-67bf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWiLQZzhfOOEwqih3qLbr2v0U6_xBYoio',
    appId: '1:313647268069:ios:2ab56e2b4901fadc09540c',
    messagingSenderId: '313647268069',
    projectId: 'messaging-app-67bf2',
    storageBucket: 'messaging-app-67bf2.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWiLQZzhfOOEwqih3qLbr2v0U6_xBYoio',
    appId: '1:313647268069:ios:2ab56e2b4901fadc09540c',
    messagingSenderId: '313647268069',
    projectId: 'messaging-app-67bf2',
    storageBucket: 'messaging-app-67bf2.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtONvghfazXAXaBPMAlUvWFbJmb_bgo3w',
    appId: '1:313647268069:web:3bffee3633e4ad7709540c',
    messagingSenderId: '313647268069',
    projectId: 'messaging-app-67bf2',
    authDomain: 'messaging-app-67bf2.firebaseapp.com',
    storageBucket: 'messaging-app-67bf2.firebasestorage.app',
  );
}
